FID = [
    {"name": "rb", "trade_unit": 10, "tick_size": 1, "vol": 10, "vol": 10},
    {"name": "i2", "trade_unit": 100, "tick_size": 0.5, "vol": 2},
    {"name": "TA", "trade_unit": 5, "tick_size": 2, "vol": 5},
    {"name": "MA", "trade_unit": 10, "tick_size": 1, "vol": 10},
    {"name": "FG", "trade_unit": 20, "tick_size": 1, "vol": 5},
    {"name": "SA", "trade_unit": 20, "tick_size": 1, "vol": 5},
    {"name": "sp", "trade_unit": 10, "tick_size": 2, "vol": 5},
    {"name": "fu", "trade_unit": 10, "tick_size": 1, "vol": 10},
    {"name": "bu", "trade_unit": 10, "tick_size": 1, "vol": 10},
    {"name": "ru", "trade_unit": 10, "tick_size": 5, "vol": 2},
    {"name": "m2", "trade_unit": 10, "tick_size": 1, "vol": 10},
    {"name": "RM", "trade_unit": 10, "tick_size": 1, "vol": 10},
    {"name": "y2", "trade_unit": 10, "tick_size": 2, "vol": 10},
    {"name": "p2", "trade_unit": 10, "tick_size": 2, "vol": 10},
    {"name": "OI", "trade_unit": 10, "tick_size": 1, "vol": 5},
    {"name": "j2", "trade_unit": 100, "tick_size": 0.5, "vol": 1},
    {"name": "SR", "trade_unit": 10, "tick_size": 1, "vol": 10},
    {"name": "CF", "trade_unit": 5, "tick_size": 5, "vol": 5},
    {"name": "c2", "trade_unit": 10, "tick_size": 1, "vol": 10},
    {"name": "ag", "trade_unit": 15, "tick_size": 1, "vol": 2},
    {"name": "zn", "trade_unit": 5, "tick_size": 5, "vol": 2},
    {"name": "cu", "trade_unit": 5, "tick_size": 10, "vol": 1},
    {"name": "IF", "trade_unit": 300, "tick_size": 0.2, "vol": 1},
    {"name": "IH", "trade_unit": 300, "tick_size": 0.2, "vol": 1},
    {"name": "IC", "trade_unit": 300, "tick_size": 0.2, "vol": 1},
    {"name": "au", "trade_unit": 1000, "tick_size": 0.02, "vol": 1},
    {"name": "UR", "trade_unit": 20, "tick_size": 1, "vol": 5},
    {"name": "v2", "trade_unit": 5, "tick_size": 1, "vol": 5},
]
